/**
 * Type declaration for vcdb MoonBit-compiled JS module.
 *
 * lib.js is generated by `moon build --target js lib` — it has no
 * TypeScript source. PersistentFFI is the SoT for function signatures.
 */
import type { PersistentFFI } from "../storage/persistent-bridge.js";

declare const _exports: PersistentFFI;
export = _exports;
