/**
 * Type declaration for vcdb MoonBit-compiled JS module.
 *
 * lib.js is generated by `moon build --target js ffi` — it has no
 * TypeScript source. WasmModule (ffi/types.ts) is the SoT for signatures.
 */
import type { WasmModule } from "../ffi/types.js";

declare const _exports: WasmModule;
export = _exports;
